### ISSUE TITLE
Facing OS not supported issue on jetson nano 4gb running 20.04

### ISSUE THREAD

**Issue by tanmayyb** [Tiryoh/ros2_setup_scripts_ubuntu#35]
I am using ubuntu 20.04 on Jetson Nano 4gb and facing this weird issue where it says focal is not supported but it should be.

![image](https://user-images.githubusercontent.com/72982560/192077498-2d7a37c7-e568-4f8e-a6cc-fd6cd41f3f73.png)

I am using this script:
https://github.com/Tiryoh/ros2_setup_scripts_ubuntu/blob/master/ros2-foxy-desktop-main.sh

and this is my system info:
![image](https://user-images.githubusercontent.com/72982560/192077575-2cd6f99c-d7cd-4fb1-8449-aa0321bd60d3.png)

**Comment by tanmayyb** [comment]
Sorry I just did 
`chmod +x <filename>`
and then ./<filename>

also changed header to `#!/bin/bash` and it started working.

**Comment by tanmayyb** [comment]
for ref:
https://stackoverflow.com/questions/3401183/bash-syntax-error-not-found

**Comment by Tiryoh** [comment]
Thanks for you report.
The cause of this issue is that the shell script is executed by specifying "sh"(`/bin/sh`).

If you run `./run.sh` according to the README, you won't get an error. Since shebang specifies bash, no change is required.
If the file permissions are messed up, change the file permissions with `chmod +x ./run.sh && ./run.sh` or try `bash ./run.sh`.
